_target_: lerobot.common.robot_devices.robots.koch.KochRobot
robot_type: aloha
calibration_path: .cache/calibration/aloha.pkl
leader_arms:
  left:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyDXL_leader_left
    # port: /dev/tty.usbserial-FT89FM77
    motors:  # window_x
      # name: (index, model)
      waist: [1, xm430-w350]
      shoulder_a: [2, xm430-w350]
      shoulder_b: [3, xm430-w350]
      elbow_a: [4, xm430-w350]
      elbow_b: [5, xm430-w350]
      forearm_roll: [6, xm430-w350]
      wrist_angle: [7, xm430-w350]
      wrist_rotate: [8, xl430-w250]
      gripper: [9, xc430-w150]
  right:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyDXL_leader_right
    # port: /dev/tty.usbserial-FT891KPN
    motors:  # window_x
      # name: (index, model)
      waist: [1, xm430-w350]
      shoulder_a: [2, xm430-w350]
      shoulder_b: [3, xm430-w350]
      elbow_a: [4, xm430-w350]
      elbow_b: [5, xm430-w350]
      forearm_roll: [6, xm430-w350]
      wrist_angle: [7, xm430-w350]
      wrist_rotate: [8, xl430-w250]
      gripper: [9, xc430-w150]

follower_arms:
  left:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyDXL_follower_left
    # port: /dev/tty.usbserial-FT891KBG
    motors:
      # name: [index, model]
      waist: [1, xm540-w270]
      shoulder_a: [2, xm540-w270]
      shoulder_b: [3, xm540-w270]
      elbow_a: [4, xm540-w270]
      elbow_b: [5, xm540-w270]
      forearm_roll: [6, xm540-w270]
      wrist_angle: [7, xm540-w270]
      wrist_rotate: [8, xm430-w350]
      gripper: [9, xm430-w350]
  right:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyDXL_follower_right
    # port: /dev/tty.usbserial-FT89FM09
    motors:
      # name: [index, model]
      waist: [1, xm540-w270]
      shoulder_a: [2, xm540-w270]
      shoulder_b: [3, xm540-w270]
      elbow_a: [4, xm540-w270]
      elbow_b: [5, xm540-w270]
      forearm_roll: [6, xm540-w270]
      wrist_angle: [7, xm540-w270]
      wrist_rotate: [8, xm430-w350]
      gripper: [9, xm430-w350]
cameras:
  cam_high:
    _target_: lerobot.common.robot_devices.cameras.intelrealsense.IntelRealSenseCamera
    camera_index: 128422271347
    fps: 30
    width: 640
    height: 480
  cam_low:
    _target_: lerobot.common.robot_devices.cameras.intelrealsense.IntelRealSenseCamera
    camera_index: 130322270656
    fps: 30
    width: 640
    height: 480
  cam_left_wrist:
    _target_: lerobot.common.robot_devices.cameras.intelrealsense.IntelRealSenseCamera
    camera_index: 218622272670
    fps: 30
    width: 640
    height: 480
  cam_right_wrist:
    _target_: lerobot.common.robot_devices.cameras.intelrealsense.IntelRealSenseCamera
    camera_index: 130322272300
    fps: 30
    width: 640
    height: 480
