_target_: lerobot.common.robot_devices.robots.arx.ARXRobot
leader_arms:
  left:
    model: L5
    interface_name: enx5c5310ecc0ec
    urdf_path: "lerobot/models/arx5.urdf"
follower_arms:
  left:
    model: L5
    interface_name: enx5c5310ecc38c
    urdf_path: "lerobot/models/arx5.urdf"
  
