_target_: lerobot.common.robot_devices.robots.arx5.ARX5Robot
leader_arms:
  left:
    model: L5
    interface_name: enx5c5310ecc0ec
    urdf_path: lerobot/models/arx5.urdf
    dof: 6
follower_arms:
  left:
    model: L5
    interface_name: enx5c5310ecc38c
    urdf_path: lerobot/models/arx5.urdf
    dof: 6
cameras:
  front:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
  wrist:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 2
    fps: 30
    width: 640
    height: 480

# python lerobot/scripts/control_robot.py record --robot-path lerobot/configs/robot/arx5.yaml --fps 50 --root tmp/data --num-episodes 1 --run-compute-stats 0
# python lerobot/scripts/control_robot.py teleoperate --robot-path lerobot/configs/robot/arx5.yaml --fps 50
