_target_: lerobot.common.robot_devices.robots.arx5.ARX5Robot
leader_arms:
  left:
    model: L5
    interface_name: enx5c5310ecc0ec
    urdf_path: lerobot/models/arx5.urdf
    dof: 6
  # right:
  #   model: L5
  #   interface_name: enx5c5310ec6299
  #   urdf_path: lerobot/models/arx5.urdf
  #   dof: 6
follower_arms:
  left:
    model: L5
    interface_name: enx5c5310ecc38c
    urdf_path: lerobot/models/arx5.urdf
    dof: 6
  # right:
  #   model: L5
  #   interface_name: enx5c5310ecc90b
  #   urdf_path: lerobot/models/arx5.urdf
  #   dof: 6
cameras:
  front:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
  wrist:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 2
    fps: 30
    width: 640
    height: 480
  # right_wrist:
  #   _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
  #   camera_index: 4
  #   fps: 30
  #   width: 640
  #   height: 480

# python lerobot/scripts/control_robot.py record --robot-path lerobot/configs/robot/arx5.yaml --fps 50 --root data --repo-id villekuosmanen/pick_coffee_prop_test --num-episodes 5
# python lerobot/scripts/control_robot.py teleoperate --robot-path lerobot/configs/robot/arx5.yaml --fps 50
# DATA_DIR=data python lerobot/scripts/train.py dataset_repo_id=villekuosmanen/pick_coffee_prop_test policy=act_arx5_real env=arx5_real hydra.run.dir=outputs/train/act_arx5_test hydra.job.name=act_arx5_test device=cuda wandb.enable=true