# @package _global_

fps: 30

eval:
  # `use_async_envs` specifies whether to use asynchronous environments (multiprocessing).
  # set it to false to avoid EGL problem of the ACT env
  # https://github.com/huggingface/lerobot/pull/358#discussion_r1714089788
  use_async_envs: false

env:
  name: dora
  task: DoraAloha-v0
  state_dim: 14
  action_dim: 14
  fps: ${fps}
  episode_length: 400
  gym:
    fps: ${fps}
