# @package _global_

fps: 10

env:
  name: rlbench
  task: reach_target-vision-v0
  state_dim: 8
  action_dim: 8
  fps: ${fps}
  episode_length: 200
  # gym:
    # obs_type: pixels_agent_pos
    # render_mode: rgb_array
