# @package _global_

fps: 15

eval:
  # `use_async_envs` specifies whether to use asynchronous environments (multiprocessing).
  # set it to false to avoid EGL problem of the ACT env
  # https://github.com/huggingface/lerobot/pull/358#discussion_r1714089788
  use_async_envs: false

env:
  name: xarm
  task: XarmLift-v0
  image_size: 84
  state_dim: 4
  action_dim: 4
  fps: ${fps}
  episode_length: 200
  gym:
    obs_type: pixels_agent_pos
    render_mode: rgb_array
    visualization_width: 384
    visualization_height: 384
