name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}


jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATA_DIR: tests/data
      MUJOCO_GL: egl
    steps:
      - name: Add SSH key for installing envs
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # cache: ${{ (github.ref == 'refs/heads/main') && 'pip' || '' }}
          # cache-dependency-path: pyproject.toml

      - name: Install EGL
        run: sudo apt-get update && sudo apt-get install -y libegl1-mesa-dev

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test, aloha, xarm, pusht]"

      - name: debug info
        run: |
          which python
          python --version
          python -c "import site; print(site.getsitepackages())"
          python -c "import torch; print(torch.cuda.is_available)"


      - name: Tailscale Wait
        if: always()
        uses: huggingface/tailscale-action@v1
        with:
          waitForSSH: true
          authkey: ${{ secrets.TAILSCALE_SSH_AUTHKEY }}
          slackChannel: ${{ secrets.SLACK_CIFEEDBACK_CHANNEL }}
          slackToken: ${{ secrets.SLACK_CIFEEDBACK_BOT_TOKEN }}

      - name: Test with pytest
        run: pytest -v --cov=./lerobot tests

      - name: Test end-to-end
        run: make test-end-to-end
